'use client';

import { useState, useEffect, useCallback } from 'react';
import { CardItem } from '@/lib/types';

export interface ItineraryItem {
  id: string;
  card: CardItem;
  dayIndex: number; // -1 = unassigned
  order: number;
}

export interface ItineraryData {
  days: number;
  items: ItineraryItem[];
}

const STORAGE_KEY = 'backpackbuddy-itinerary';

function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`;
}

export function useItinerary() {
  const [days, setDays] = useState(3);
  const [items, setItems] = useState<ItineraryItem[]>([]);
  const [initialized, setInitialized] = useState(false);

  // Load from localStorage
  useEffect(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY);
      if (saved) {
        const parsed = JSON.parse(saved) as ItineraryData;
        if (parsed.days && Array.isArray(parsed.items)) {
          setDays(parsed.days);
          setItems(parsed.items);
        }
      }
    } catch {}
    setInitialized(true);
  }, []);

  // Save to localStorage
  useEffect(() => {
    if (initialized) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify({ days, items }));
    }
  }, [days, items, initialized]);

  const importFromSaved = useCallback((savedCards: CardItem[]) => {
    const newItems: ItineraryItem[] = savedCards.map((card, i) => ({
      id: generateId(),
      card,
      dayIndex: -1,
      order: i,
    }));
    setItems(newItems);
  }, []);

  const assignToDay = useCallback((itemId: string, dayIndex: number) => {
    setItems((prev) => {
      const maxOrder = prev.filter((i) => i.dayIndex === dayIndex).length;
      return prev.map((item) =>
        item.id === itemId ? { ...item, dayIndex, order: maxOrder } : item
      );
    });
  }, []);

  const removeItem = useCallback((itemId: string) => {
    setItems((prev) => prev.filter((i) => i.id !== itemId));
  }, []);

  const unassignItem = useCallback((itemId: string) => {
    setItems((prev) =>
      prev.map((item) => (item.id === itemId ? { ...item, dayIndex: -1 } : item))
    );
  }, []);

  const moveItemUp = useCallback((itemId: string) => {
    setItems((prev) => {
      const item = prev.find((i) => i.id === itemId);
      if (!item || item.dayIndex === -1) return prev;
      const dayItems = prev
        .filter((i) => i.dayIndex === item.dayIndex)
        .sort((a, b) => a.order - b.order);
      const idx = dayItems.findIndex((i) => i.id === itemId);
      if (idx <= 0) return prev;
      const above = dayItems[idx - 1];
      return prev.map((i) => {
        if (i.id === itemId) return { ...i, order: above.order };
        if (i.id === above.id) return { ...i, order: item.order };
        return i;
      });
    });
  }, []);

  const moveItemDown = useCallback((itemId: string) => {
    setItems((prev) => {
      const item = prev.find((i) => i.id === itemId);
      if (!item || item.dayIndex === -1) return prev;
      const dayItems = prev
        .filter((i) => i.dayIndex === item.dayIndex)
        .sort((a, b) => a.order - b.order);
      const idx = dayItems.findIndex((i) => i.id === itemId);
      if (idx >= dayItems.length - 1) return prev;
      const below = dayItems[idx + 1];
      return prev.map((i) => {
        if (i.id === itemId) return { ...i, order: below.order };
        if (i.id === below.id) return { ...i, order: item.order };
        return i;
      });
    });
  }, []);

  const getUnassigned = useCallback(() => {
    return items.filter((i) => i.dayIndex === -1);
  }, [items]);

  const getItemsForDay = useCallback(
    (dayIndex: number) => {
      return items.filter((i) => i.dayIndex === dayIndex).sort((a, b) => a.order - b.order);
    },
    [items]
  );

  const exportAsText = useCallback(() => {
    let text = '🎒 BackpackBuddy Trip Itinerary\n';
    text += '═'.repeat(35) + '\n\n';

    for (let d = 0; d < days; d++) {
      const dayItems = getItemsForDay(d);
      text += `📅 Day ${d + 1}\n`;
      text += '─'.repeat(25) + '\n';
      if (dayItems.length === 0) {
        text += '  (No activities yet)\n';
      } else {
        for (const item of dayItems) {
          const icon = item.card.type === 'eat' ? '🍴' : item.card.type === 'stay' ? '🏨' : item.card.type === 'transport' ? '🚌' : item.card.type === 'plan' ? '📋' : '💡';
          text += `  ${icon} ${item.card.title}\n`;
          for (const b of item.card.bullets) {
            text += `     • ${b}\n`;
          }
        }
      }
      text += '\n';
    }

    text += '\nGenerated by BackpackBuddy AU';
    return text;
  }, [days, getItemsForDay]);

  return {
    days,
    setDays,
    items,
    importFromSaved,
    assignToDay,
    removeItem,
    unassignItem,
    moveItemUp,
    moveItemDown,
    getUnassigned,
    getItemsForDay,
    exportAsText,
  };
}
